version: '3.6'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - elastic
      - kibana
    depends_on:
      - elastic
      - kibana
    networks:
      - backend
    expose: 
      - 3000
  
  elastic:
    image: elasticsearch:6.5.0
    volumes:
      - elastic:/data/db/
    networks:
      - backend
    ports:
      - "9200:9200"
    expose:
      - 9200

  kibana:
    image: kibana:6.5.0
    networks:
      - backend
    ports:
      - "5601:5601"
    expose:
      - 5601

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks: 
      - backend
    

networks:
  backend:

volumes:
  elastic: